---
- hosts: vagrant
  sudo: true
  vars:
    hostname: vagrant-ansible-rails
    environtment: vagrant
    ruby_version: 2.2.2
    rbenv_root: /home/vagrant/.rbenv
    rbenv_bin: /home/vagrant/.rbenv/libexec/rbenv
    group: ops
    # NOTE: Password must be hashed. this is created with:
    # openssl passwd -salt salty -1 あなたのパスワード
    user_password: $1$salty$9LqYQSloA.dNYnW6izxVe/
    user: ops
    rails_directory: /home/ops/life_with_beer
  roles:
    - common
    - mysql
    - deploy_user
    - firewalld
    - ruby
    - rails
