---
# package installation
- name: yum update
  become: yes
  become_method: sudo  
  shell: bash -lc "yum update"
- name: install basic packages
  yum: name={{ item }} state=installed
  with_items:
    - git
    - curl
    - wget
    - libselinux-python
    - ruby-devel
    - readline-devel
    - ncurses-devel
    - gdbm-devel
    - openssl-devel
    - libxslt-devel
    - sqlite-devel
    - libyaml
    - libyaml-devel
    - tcl-devel
    - libffi-devel
    - gcc
    - libxml2
    - libxml2-devel
    - libxslt
    - libxslt-devel
    - ImageMagick
    - ImageMagick-devel

- name: install Development Tool
  become: yes
  become_method: sudo
  shell: yum -y groupinstall "Development Tools"

# timezone
- name: set timezone
  file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link force=yes

# hostname
- name: set hostname
  hostname: name={{ hostname }}
- name: set /etc/hosts
  lineinfile: dest=/etc/hosts regexp=^127\.0\.0\.1 line='127.0.0.1 {{ hostname }} localhost localhost.localdomain'

# DNS Info mation
- name: update resolv.conf
  shell: chmod a+w /etc/resolv.conf && echo 'options single-request-reopen' >> /etc/resolv.conf
