---
- name: Install Ruby
  yum: name={{ item }} state=installed
  with_items:
    - epel-release
    - ruby
    - mysql-devel
  tags: ruby
- name: check if qtwebkit
  shell: bash -c 'yum search qtwebkit-devel'
  register: result
  failed_when: result.rc not in [0, 1]
  tags: ruby
  
- name: setup qtwebkit
  yum: name=http://rpm.pbone.net/index.php3/stat/3/srodzaj/2/search/qtwebkit-2.3.4-6.el7.1.src.rpm state=present
  when: result.rc == 1
  tags: ruby
  
- name: install qtweb-kit
  yum: name=qtwebkit-devel state=installed

- name: check if rvm
  shell: bash -c 'ls -al /usr/local/rvm/bin/rvm'
  register: rvm_result
  failed_when: rvm_result.rc not in [0, 1]
  tags: ruby
  
- name: Install GPG
  shell: bash -c "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"
  when: rvm_result.rc == 1
  tags: ruby
  
- name: Install RVM
  shell: bash -c "curl -sSL https://get.rvm.io | bash -s stable --ruby={{ ruby_version }}"
  when: rvm_result.rc == 1
  tags: ruby
  
- name: Install Ruby with rvm
  when: rvm_result.rc == 1
  shell: bash -c "/usr/local/rvm/bin/rvm install {{ ruby_version }}"
  
- name: install bundler
  shell: bash -lc "gem install bundler"
  tags: ruby
  
- name: check if Capybara webkit symlink
  shell: bash -c 'which qmake'
  register: result
  failed_when: result.rc not in [0, 1]
  tags: ruby
  
- name: symlink for Capybara webkit
  become: yes
  become_method: sudo
  shell: bash -c "ln -s /usr/lib64/qt4/bin/qmake /usr/bin/qmake"
  when: result.rc == 1
  tags: ruby
  
- name: create shared directory
  shell: bash -lc "mkdir /home/ops/shared; mkdir -p /home/ops/shared/tmp/sockets; mkdir -p /home/ops/shared/tmp/pids; mkdir /home/ops/shared/log; ln -s /home/ops/shared /home/ops/life_with_beer/shared"
  tags: ruby
- name: chown and chgrp
  shell: bash -lc "chown -R ops /home/ops/shared; chgrp -R ops /home/ops/shared;chown -R ops /home/ops/life_with_beer; chgrp -R ops /home/ops/life_with_beer"
  tags: ruby
