---
- name: prepare node env
  shell: bash -lc "curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -"
  tags: rails
- name: install node with yum
  yum: name={{ item }} state=installed
  with_items:
    - nodejs
    - gcc-c++
    - make
- name: start Unicorn
  shell: bash -lc "ch /home/ops/life_with_beer; bundle exec unicorn_rails -c config/unicorn.rb -E production -D"
  tags: rails
