---
- name: remove MariaDB
  yum: name={{ item }} state=absent
  with_items:
    - mariadb
    - mariadb-libs
    - mariadb-server
  tags: mysql
- name: add repositry
  yum: name={{ item }}
  with_items:
    - http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
  tags: mysql
- name: install MySQL
  shell: yum -y install mysql-community-server
  tags: mysql
- name: locate my.cnf
  copy: src=/vagrant/provision/mysql/my.cnf dest=/etc/my.cnf mode=0644 owner=root group=root
  tags: mysql
- name: start MySQL
  shell: systemctl enable mysqld.service; systemctl start mysqld.service
  tags: mysql
